# Generated by Django 3.2.10 on 2021-12-30 02:26

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=False, quality=90, size=[400, 400], upload_to='projects'),
        ),
    ]
